In [25]:
"""
Alexander Hay
ME449

Chapter 5 - Quiz
"""
import numpy as np
import modern_robotics as mr

In [26]:
# Problem 1

xa = np.transpose([[0,0,1]])
ya = np.transpose([[-1,0,0]])
za = np.transpose([[0,-1,0]])

p_sa = np.transpose([[0,0,1]])

Rsa = xa
Rsa = np.append(Rsa, ya,axis=1)
Rsa = np.append(Rsa, za,axis=1)
Tsa = np.append(Rsa,p_sa,axis=1)
Tsa = np.append(Tsa,[[0,0,0,1]],axis=0)
Tas = mr.TransInv(Tsa)

print(Tsa)

[[ 0 -1  0  0]
 [ 0  0 -1  0]
 [ 1  0  0  1]
 [ 0  0  0  1]]


In [27]:
# Problem 2

xb = np.transpose([[1,0,0]])
yb = np.transpose([[0,0,-1]])
zb = np.transpose([[0,1,0]])

p_sb = np.transpose([[0,2,0]])

Rsb = xb
Rsb = np.append(Rsb, yb,axis=1)
Rsb = np.append(Rsb, zb,axis=1)
Tsb = np.append(Rsb,p_sb,axis=1)
Tsb = np.append(Tsb,[[0,0,0,1]],axis=0)

Tbs = mr.TransInv(Tsb)

print(Tbs)

[[ 1  0  0  0]
 [ 0  0 -1  0]
 [ 0  1  0 -2]
 [ 0  0  0  1]]


In [28]:
# Problem 3

Tab = np.dot(Tas,Tsb)

print(Tab)

[[ 0 -1  0 -1]
 [-1  0  0  0]
 [ 0  0 -1 -2]
 [ 0  0  0  1]]


In [29]:
# Problem 4

print("T is in frame {s}")

T is in frame {s}


In [33]:
# Problem 5

# p_bs = np.dot(Rsb, p_sb)
# or
p_bs = mr.TransToRp(mr.TransInv(Tsb))[1]
print(p_bs)

[ 0  0 -2]


In [32]:
# Problem 6

print("q is not in {b} coordinates")

q is not in {b} coordinates


In [36]:
# Problem 7

V_s = np.transpose([[3,2,1,-1,-2,-3]])

V_a = np.dot(mr.Adjoint(Tas),V_s)

print(V_a)

[[ 1.]
 [-3.]
 [-2.]
 [-3.]
 [-1.]
 [ 5.]]


In [35]:
# Problem 8

2.0944

2.0944

In [ ]:
# Problem 9

[[-0.61727288, -0.70368982,  0.35184491,  1.05553472],
 [ 0.70368982, -0.2938183 ,  0.64690915,  1.94072745],
 [-0.35184491,  0.64690915,  0.67654542, -0.97036373],
 [ 0.        ,  0.        ,  0.        ,  1.        ]]

In [37]:
# Problem 10

F_b = np.transpose([[1,0,0,2,1,0]])

Tba = mr.TransInv(Tab)



F_a = np.dot(mr.Adjoint(Tba).T,F_b)

print(F_a)

[[-4.]
 [ 1.]
 [ 2.]
 [-1.]
 [-2.]
 [ 0.]]


In [38]:
# Problem 11

T = np.array([[ 0,-1, 0, 3],
              [ 1, 0, 0, 0],
              [ 0, 0, 1, 1],
              [ 0, 0, 0, 1]])

print(mr.TransInv(T))

[[ 0  1  0  0]
 [-1  0  0  3]
 [ 0  0  1 -1]
 [ 0  0  0  1]]


In [39]:
# Problem 12

V = np.transpose([[1,0,0,0,2,3]])

print(mr.VecTose3(V))

[[ 0.  0.  0.  0.]
 [ 0.  0. -1.  2.]
 [ 0.  1.  0.  3.]
 [ 0.  0.  0.  0.]]


In [40]:
# Problem 13

s = [1,0,0]
q = [0,0,2]
h = 1

print(mr.ScrewToAxis(q,s,h))

[1 0 0 1 2 0]


In [41]:
# Problem 14

T = np.array([[0, -1.5708, 0, 2.3562],
              [1.5708, 0, 0, -2.3562],
              [0, 0, 0, 1],
              [0,0,0,0]])

print(mr.MatrixExp6(T))

[[-3.67320510e-06 -1.00000000e+00  0.00000000e+00  3.00000551e+00]
 [ 1.00000000e+00 -3.67320510e-06  0.00000000e+00  5.50981777e-06]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  1.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [42]:
# Problem 15

T = np.array([[0,-1, 0, 3],
              [1, 0, 0, 0],
              [0, 0, 1, 1],
              [0, 0, 0, 1]])

print(mr.MatrixLog6(T))

[[ 0.         -1.57079633  0.          2.35619449]
 [ 1.57079633  0.          0.         -2.35619449]
 [ 0.          0.          0.          1.        ]
 [ 0.          0.          0.          0.        ]]
