In [1]:
"""
Alexander Hay
ME449

Chapter 5 - Quiz
"""
import numpy as np
from numpy import linalg as la
import modern_robotics as mr

In [2]:
""" Problem 1"""
# Given variables:
l1,l2,l3=1,1,1

th1 = 0
th2 = np.pi/4
th3 = 0

th = [th1,th2,th3]

Fs = np.transpose([[0,0,0,2,0,0]])

# Find Js
j1 = np.transpose([[0,0,1,0,0,0]])

j2v1 = l1*np.sin(th1)
j2v2 = -l1*np.cos(th1)
j2 = np.transpose([[0,0,1,j2v1,j2v2,0]])

j3v1 = (l1*np.sin(th1)) + (l2*np.sin(th1+th2))
j3v2 = (-l1*np.cos(th1)) - (l2*np.cos(th1+th2))
j3 = np.transpose([[0,0,1,j3v1,j3v2,0]])

J = np.append(j1,j2,axis=1)
J = np.append(J,j3,axis=1)

# Solve for T
T = np.dot(J.T,Fs)

print("Problem 1")
print()
print("Given Vairables:")
print("theta:" + str(th))
print()
print("Fs.T:" + str(Fs.T))
print()
print("Js:" + str(J))
print()
print("Solve: T")
print("T:" + str(T))

Problem 1

Given Vairables:
theta:[0, 0.7853981633974483, 0]

Fs.T:[[0 0 0 2 0 0]]

Js:[[ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 1.          1.          1.        ]
 [ 0.          0.          0.70710678]
 [ 0.         -1.         -1.70710678]
 [ 0.          0.          0.        ]]

Solve: T
T:[[0.        ]
 [0.        ]
 [1.41421356]]


In [3]:
"""Problem 2"""
# Given variables:
l1,l2,l3,l4=1,1,1,1

th1,th2=0,0
th3=np.pi/2
th4=-np.pi/2

th = np.array([th1,th2,th3,th4])

Fb = np.transpose([0,0,10,10,10,0])

# Find Body Jacobian; wbz, vbx, vby given
jb_wx = np.array([[0,0,0,0],[0,0,0,0],[1,1,1,1]])
# jb_wy = np.array([0,0,0,0])
# jb_wz = np.array([1,1,1,1])

jb_21 = (l3*np.sin(th4)) + (l2*np.sin(th3+th4)) + (l1*np.sin(th2+th3+th4))
jb_22 = (l3*np.sin(th4)) + (l2*np.sin(th3+th4))
jb_23 = (l3*np.sin(th4))
jb_vx = np.array([[jb_21,jb_22,jb_23,0]])

jb_31 = l4 + (l3*np.cos(th4)) + (l2*np.cos(th3+th4)) + (l1*np.cos(th2+th3+th4))
jb_32 = l4 + (l3*np.cos(th4)) + (l2*np.cos(th3+th4))
jb_33 = l4 + (l3*np.cos(th4))
jb_vy = np.array([[jb_31, jb_32, jb_33, l4]])

jb_vz = np.array([[0,0,0,0]])

Jb = jb_wx
# Jb = np.append(Jb,jb_wy,axis=0)
# Jb = np.append(Jb,jb_wz,axis=0)
Jb = np.append(Jb,jb_vx,axis=0)
Jb = np.append(Jb,jb_vy,axis=0)
Jb = np.append(Jb,jb_vz,axis=0)

# Solve for T
T = np.dot(Jb.T,Fb)

print("Problem 2")
print()
print("Given Vairables:")
print("theta:" + str(th))
print()
print("Fb:" + str(Fb.T))
print()
print("Jb:" + str(Jb))
print()
print("Solve for T")
print("T:" + str(T))

Problem 2

Given Vairables:
theta:[ 0.          0.          1.57079633 -1.57079633]

Fb:[ 0  0 10 10 10  0]

Jb:[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 1.  1.  1.  1.]
 [-1. -1. -1.  0.]
 [ 3.  2.  1.  1.]
 [ 0.  0.  0.  0.]]

Solve for T
T:[30. 20. 10. 20.]


In [4]:
"""Problem 3"""
# Given variables:

Slist = [[0,         1,         0],
         [0,         0,         0],
         [1,         0,         0],
         [0,         0,         0],
         [0,         2,         1],
         [0,         0,         0]]

l1 = 2
l2 = 3

thetalist = [np.pi/2, np.pi/2, 1]

print("Slist")
print(Slist)
print()
print("thetalist:")
print(thetalist)
print()
print("Using mr.JacobianSpace(Slist,thetalist)")
print("Js:")
print(str(mr.JacobianSpace(Slist,thetalist)))

Slist
[[0, 1, 0], [0, 0, 0], [1, 0, 0], [0, 0, 0], [0, 2, 1], [0, 0, 0]]

thetalist:
[1.5707963267948966, 1.5707963267948966, 1]

Using mr.JacobianSpace(Slist,thetalist)
Js:
[[ 0.00000000e+00  1.11022302e-16  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -2.00000000e+00 -1.11022302e-16]
 [ 0.00000000e+00  2.22044605e-16  1.23259516e-32]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [5]:
"""Problem 4"""
# Same process as above
Blist = [[0, -1,  0],
         [1,  0,  0],
         [0,  0,  0],
         [3,  0,  0],
         [0,  3,  0],
         [0,  0,  1]]

print("Using mr.JacobianBody(Blist,thetalist)")
mr.JacobianBody(Blist,thetalist)

Using mr.JacobianBody(Blist,thetalist)


array([[ 0.00000000e+00, -1.00000000e+00,  0.00000000e+00],
       [ 1.11022302e-16,  0.00000000e+00,  0.00000000e+00],
       [ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 4.44089210e-16,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  4.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [6]:
"""Problem 5"""
# Given variables:

l1 = 0.550 # (m) meters
l2 = 0.300
l3 = 0.060
w1 = 0.045

# Body Jacobian Jb
j1 = np.transpose([[0,0,1,-0.105,-0.889,0]])
j2 = np.transpose([[-1,0,0,0,0.006,-0.105]])
j3 = np.transpose([[0,1,0,0.006,0,0.889]])
j4 = np.transpose([[0,0,1,-0.045,-0.844,0]])
j5 = np.transpose([[-1,0,0,0,0.006,0]])
j6 = np.transpose([[0,1,0,0.006,0,0]])
j7 = np.transpose([[0,0,1,0,0,0]])

Jb = np.append(j1,j2,axis=1)
Jb = np.append(Jb,j3,axis=1)
Jb = np.append(Jb,j4,axis=1)
Jb = np.append(Jb,j5,axis=1)
Jb = np.append(Jb,j6,axis=1)
Jb = np.append(Jb,j7,axis=1)

# Screw Axis B
b1 = np.transpose([[0,0,1,0,0,0]])
b2 = np.transpose([[0,1,0,(l1+l2+l3),0,0]])
b3 = np.transpose([[0,0,1,0,0,0]])
b4 = np.transpose([[0,1,0,(l2+l3),0,w1]])
b5 = np.transpose([[0,0,1,0,0,0]])
b6 = np.transpose([[0,1,0,l3,0,0]])
b7 = np.transpose([[0,0,1,0,0,0]])

B = np.append(b1,b2,axis=1)
B = np.append(B,b3,axis=1)
B = np.append(B,b4,axis=1)
B = np.append(B,b5,axis=1)
B = np.append(B,b6,axis=1)
B = np.append(B,b7,axis=1)

# Extract linear velocity portion Jv
jbw, jbv = np.rint(np.split(Jb,2))

# Calculate the directions and lengths of the principal semi-axes 
# of the three-dimensional linear velocity manipulability ellipsoid based on Jw.

# a_w = np.dot(jbw,jbw.T)
# eval_w,evec_w = la.eig(a_w)
# len_w = np.sqrt(eval_w)

# Calculate the directions and lengths of the principal semi-axes 
# of the three-dimensional linear velocity manipulability ellipsoid based on Jv.
a_v = np.dot(jbv,jbv.T)
eval_v,evec_v = la.eig(a_v)
len_v = np.sqrt(eval_v)


# Give a unit vector to represent the direction of the longest principal semi-axis

# evec_v - directions of principal semi-axes for linear velocity manipulability ellipsoid
# len_v - lengths of principal semi-axes for linear velocity manipulability ellipsoid


# a_w = np.dot(jbw,jbw.T)
# eval_w,evec_w = la.eig(a_w)
# len_w = np.sqrt(eval_w)


# len_w - lengths of principal semi-axes for angular velocity manipulability ellipsoid
# len_v - lengths of principal semi-axes for linear velocity manipulability ellipsoid
# evec_w - directions of principal semi-axes for angular velocity manipulability ellipsoid
# evec_v - directions of principal semi-axes for linear velocity manipulability ellipsoid

print("Jb:")
print(Jb)
print()
print("B Screw Axis:")
print(B)
print()
print("Linear Velocity Portion of Jb")
print(jbv)
print()
print("Direction of Principal Semi-Axis of Linear Velocity Manipulability Ellipsoid")
print(evec_v)
print()
print("Length of Principal Semi-Axis of Linear Velocity Manipulability Ellipsoid")
print(len_v)


Jb:
[[ 0.    -1.     0.     0.    -1.     0.     0.   ]
 [ 0.     0.     1.     0.     0.     1.     0.   ]
 [ 1.     0.     0.     1.     0.     0.     1.   ]
 [-0.105  0.     0.006 -0.045  0.     0.006  0.   ]
 [-0.889  0.006  0.    -0.844  0.006  0.     0.   ]
 [ 0.    -0.105  0.889  0.     0.     0.     0.   ]]

B Screw Axis:
[[0.    0.    0.    0.    0.    0.    0.   ]
 [0.    1.    0.    1.    0.    1.    0.   ]
 [1.    0.    1.    0.    1.    0.    1.   ]
 [0.    0.91  0.    0.36  0.    0.06  0.   ]
 [0.    0.    0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.045 0.    0.    0.   ]]

Linear Velocity Portion of Jb
[[-0.  0.  0. -0.  0.  0.  0.]
 [-1.  0.  0. -1.  0.  0.  0.]
 [ 0. -0.  1.  0.  0.  0.  0.]]

Direction of Principal Semi-Axis of Linear Velocity Manipulability Ellipsoid
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Length of Principal Semi-Axis of Linear Velocity Manipulability Ellipsoid
[0.         1.41421356 1.        ]
