In [2]:
"""
Alexander Hay
ME449

Chapter 5 - Quiz
"""
import numpy as np
from numpy import linalg as la
import modern_robotics as mr

In [8]:
"""Problem 5"""

# Given:
T = 5
t = 3

# Solve:
s = mr.QuinticTimeScaling(T,t)

print("s:" + str(round(s,2)))

s:0.68


In [11]:
"""Problem 6"""

# Given:
x_start = eye(4)
x_end = np.array([[0,0,1,1],[1,0,0,2],[0,1,0,3],[0,0,0,1]])

Tf = 10
N = 10
method = 3

# Solve for x_9 using Screw Trajectory

traj = mr.ScrewTrajectory(x_start, x_end, Tf, N, method)

print("x_9:")
print(traj[8])

x_9:
[[ 0.04229152 -0.04057269  0.99828116  0.93313173]
 [ 0.99828116  0.04229152 -0.04057269  1.97198558]
 [-0.04057269  0.99828116  0.04229152  2.88912137]
 [ 0.          0.          0.          1.        ]]


In [16]:
"""Problem 7"""

# Given: 
# x_start, x_end, Tf, and N are same as Problem 6
method = 5

# Solve for x_9 using Cartesian Trajectory

traj = mr.CartesianTrajectory(x_start, x_end, Tf, N, method)

print("x_9:")
print(traj[8])

x_9:
[[ 0.01404133 -0.01384686  0.99980553  0.98846721]
 [ 0.99980553  0.01404133 -0.01384686  1.97693441]
 [-0.01384686  0.99980553  0.01404133  2.96540162]
 [ 0.          0.          0.          1.        ]]
